out of restart_dir again
